# Generated by Django 3.2.18 on 2023-05-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20230503_0250'),
    ]

    operations = [

        # Now apply the actual migration
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='departures', to='flights.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='arrivals', to='flights.Airport'),
        ),
    ]
